events {
    worker_connections 1024;
}

http {
    upstream nextjs_app {
        # Para simular la persistencia de sesión como en un ALB (Sticky Sessions)
        # Esto es crucial ya que el juego guarda su estado en memoria global.
        ip_hash;
        
        # Referenciando los servicios en docker-compose
        server app1:3000;
        server app2:3000;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://nextjs_app;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}
